import = [
  "~/.config/alacritty/themes/gnome-dark.toml"
]

[font]
normal      = { family = "0xProto Nerd Font" }
size = 12

[window]
dynamic_padding = true
opacity = 1
blur = true
decorations = "none"

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = { blinking = "Always" }
