import = [
  "~/.config/alacritty/themes/gnome-dark.toml"
]

[font]
normal      = { family = "0xProto Nerd Font" }
size = 12

[window]
dynamic_padding = true
opacity = 0.95
blur = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = { blinking = "Always" }
