import = [
  "~/.config/alacritty/themes/vscode-dark.toml"
]

[font]
normal      = { family = "Cascadia Code NF", style = "Regular" }
italic      = { family = "Cascadia Code NF", style = "Italic" }
bold        = { family = "Cascadia Code NF", style = "Bold" }
bold_italic = { family = "Cascadia Code NF", style = "Bold Italic" }
size = 11

[window]
dynamic_padding = true
# opacity = 0.9
# blur = true

[colors]
# draw_bold_text_with_bright_colors = true

[cursor]
style = { blinking = "Always" }
