# preload = /home/vomaksh/Pictures/Unsplash/anil-sharma-Kpa7d_60QlU-unsplash.jpg
preload = /home/vomaksh/Pictures/Unsplash/wallhaven-ex5z1r.jpg

# wallpaper = DP-3,/home/vomaksh/Pictures/Unsplash/anil-sharma-Kpa7d_60QlU-unsplash.jpg
# wallpaper = eDP-1,/home/vomaksh/Pictures/Unsplash/anil-sharma-Kpa7d_60QlU-unsplash.jpg
wallpaper = DP-3,/home/vomaksh/Pictures/Unsplash/wallhaven-ex5z1r.jpg
wallpaper = eDP-1,/home/vomaksh/Pictures/Unsplash/wallhaven-ex5z1r.jpg
wallpaper = HDMI-A-1,/home/vomaksh/Pictures/Unsplash/wallhaven-ex5z1r.jpg

# enable splash text rendering over the wallpaper
# splash = true

# fully disable ipc
# ipc = off

